create table  rooms (
    id bigint generated by default as identity primary key,
    room_number varchar(20) not null unique ,
    price integer not null check ( price >= 0 )
);

create table  reservations (
    id bigint generated by default as identity primary key ,
    room_id bigint not null ,
    check_in_date date not null ,
    check_out_date data not null ,
    status varchar(20) not null  default 'CONFIRMED',

    foreign key (room_id) references rooms(id),
    check ( check_in_date < check_out_date ),
    check ( status in ('CONFIRMED', 'CANCELED') )
);